package utility

type countriesMap struct {
	data map[int]map[string]string
}

//TODO: think about a nicer solution

//NewCountryMap returns a new instance of the countrymap
func NewCountryMap() *countriesMap {
	countries := new(countriesMap)
	countries.data = map[int]map[string]string{
		4:   {"name": "Afghanistan", "code": "AFG"},
		8:   {"name": "Albania", "code": "ALB"},
		10:  {"name": "Antarctica", "code": "ATA"},
		12:  {"name": "Algeria", "code": "DZA"},
		16:  {"name": "American Samoa", "code": "ASM"},
		20:  {"name": "Andorra", "code": "AND"},
		24:  {"name": "Angola", "code": "AGO"},
		28:  {"name": "Antigua and Barbuda", "code": "ATG"},
		31:  {"name": "Azerbaijan", "code": "AZE"},
		32:  {"name": "Argentina", "code": "ARG"},
		36:  {"name": "Australia", "code": "AUS"},
		40:  {"name": "Austria", "code": "AUT"},
		44:  {"name": "Bahamas", "code": "BHS"},
		48:  {"name": "Bahrain", "code": "BHR"},
		50:  {"name": "Bangladesh", "code": "BGD"},
		51:  {"name": "Armenia", "code": "ARM"},
		52:  {"name": "Barbados", "code": "BRB"},
		56:  {"name": "Belgium", "code": "BEL"},
		60:  {"name": "Bermuda", "code": "BMU"},
		64:  {"name": "Bhutan", "code": "BTN"},
		68:  {"name": "Plurinational State of Bolivia", "code": "BOL"},
		70:  {"name": "Bosnia and Herzegovina", "code": "BIH"},
		72:  {"name": "Botswana", "code": "BWA"},
		74:  {"name": "Bouvet Island", "code": "BVT"},
		76:  {"name": "Brazil", "code": "BRA"},
		84:  {"name": "Belize", "code": "BLZ"},
		86:  {"name": "British Indian Ocean Territory", "code": "IOT"},
		90:  {"name": "Solomon Islands", "code": "SLB"},
		92:  {"name": "British Virgin Islands", "code": "VGB"},
		96:  {"name": "Brunei Darussalam", "code": "BRN"},
		100: {"name": "Bulgaria", "code": "BGR"},
		104: {"name": "Myanmar", "code": "MMR"},
		108: {"name": "Burundi", "code": "BDI"},
		112: {"name": "Belarus", "code": "BLR"},
		116: {"name": "Cambodia", "code": "KHM"},
		120: {"name": "Cameroon", "code": "CMR"},
		124: {"name": "Canada", "code": "CAN"},
		132: {"name": "Cabo Verde", "code": "CPV"},
		136: {"name": "Cayman Islands", "code": "CYM"},
		140: {"name": "Central African Republic", "code": "CAF"},
		144: {"name": "Sri Lanka", "code": "LKA"},
		148: {"name": "Chad", "code": "TCD"},
		152: {"name": "Chile", "code": "CHL"},
		156: {"name": "China", "code": "CHN"},
		158: {"name": "Taiwan", "code": "TWN"},
		162: {"name": "Christmas Island", "code": "CXR"},
		166: {"name": "Cocos (Keeling) Islands", "code": "CCK"},
		170: {"name": "Colombia", "code": "COL"},
		174: {"name": "Comoros", "code": "COM"},
		175: {"name": "Mayotte", "code": "MYT"},
		178: {"name": "Congo", "code": "COG"},
		180: {"name": "The Democratic Republic of the Congo", "code": "COD"},
		184: {"name": "Cook Islands", "code": "COK"},
		188: {"name": "Costa Rica", "code": "CRI"},
		191: {"name": "Croatia", "code": "HRV"},
		192: {"name": "Cuba", "code": "CUB"},
		196: {"name": "Cyprus", "code": "CYP"},
		203: {"name": "Czechia", "code": "CZE"},
		204: {"name": "Benin", "code": "BEN"},
		208: {"name": "Denmark", "code": "DNK"},
		212: {"name": "Dominica", "code": "DMA"},
		214: {"name": "Dominican Republic", "code": "DOM"},
		218: {"name": "Ecuador", "code": "ECU"},
		222: {"name": "El Salvador", "code": "SLV"},
		226: {"name": "Equatorial Guinea", "code": "GNQ"},
		231: {"name": "Ethiopia", "code": "ETH"},
		232: {"name": "Eritrea", "code": "ERI"},
		233: {"name": "Estonia", "code": "EST"},
		234: {"name": "Faroe Islands", "code": "FRO"},
		238: {"name": "Falkland Islands (Malvinas)", "code": "FLK"},
		239: {"name": "South Georgia and the South Sandwich Islands", "code": "SGS"},
		242: {"name": "Fiji", "code": "FJI"},
		246: {"name": "Finland", "code": "FIN"},
		248: {"name": "Åland Islands", "code": "ALA"},
		250: {"name": "France", "code": "FRA"},
		254: {"name": "French Guiana", "code": "GUF"},
		258: {"name": "French Polynesia", "code": "PYF"},
		260: {"name": "French Southern Territories", "code": "ATF"},
		262: {"name": "Djibouti", "code": "DJI"},
		266: {"name": "Gabon", "code": "GAB"},
		268: {"name": "Georgia", "code": "GEO"},
		270: {"name": "Gambia", "code": "GMB"},
		275: {"name": "State of Palestine", "code": "PSE"},
		276: {"name": "Germany", "code": "DEU"},
		288: {"name": "Ghana", "code": "GHA"},
		292: {"name": "Gibraltar", "code": "GIB"},
		296: {"name": "Kiribati", "code": "KIR"},
		300: {"name": "Greece", "code": "GRC"},
		304: {"name": "Greenland", "code": "GRL"},
		308: {"name": "Grenada", "code": "GRD"},
		312: {"name": "Guadeloupe", "code": "GLP"},
		316: {"name": "Guam", "code": "GUM"},
		320: {"name": "Guatemala", "code": "GTM"},
		324: {"name": "Guinea", "code": "GIN"},
		328: {"name": "Guyana", "code": "GUY"},
		332: {"name": "Haiti", "code": "HTI"},
		334: {"name": "Heard Island and McDonald Islands", "code": "HMD"},
		336: {"name": "Holy See (Vatican City State)", "code": "VAT"},
		340: {"name": "Honduras", "code": "HND"},
		344: {"name": "Hong Kong", "code": "HKG"},
		348: {"name": "Hungary", "code": "HUN"},
		352: {"name": "Iceland", "code": "ISL"},
		356: {"name": "India", "code": "IND"},
		360: {"name": "Indonesia", "code": "IDN"},
		364: {"name": "Islamic Republic of Iran", "code": "IRN"},
		368: {"name": "Iraq", "code": "IRQ"},
		372: {"name": "Ireland", "code": "IRL"},
		376: {"name": "Israel", "code": "ISR"},
		380: {"name": "Italy", "code": "ITA"},
		384: {"name": "Côte d'Ivoire", "code": "CIV"},
		388: {"name": "Jamaica", "code": "JAM"},
		392: {"name": "Japan", "code": "JPN"},
		398: {"name": "Kazakhstan", "code": "KAZ"},
		400: {"name": "Jordan", "code": "JOR"},
		404: {"name": "Kenya", "code": "KEN"},
		408: {"name": "Democratic People's Republic of Korea", "code": "PRK"},
		410: {"name": "Republic of Korea", "code": "KOR"},
		414: {"name": "Kuwait", "code": "KWT"},
		417: {"name": "Kyrgyzstan", "code": "KGZ"},
		418: {"name": "Lao People's Democratic Republic", "code": "LAO"},
		422: {"name": "Lebanon", "code": "LBN"},
		426: {"name": "Lesotho", "code": "LSO"},
		428: {"name": "Latvia", "code": "LVA"},
		430: {"name": "Liberia", "code": "LBR"},
		434: {"name": "Libya", "code": "LBY"},
		438: {"name": "Liechtenstein", "code": "LIE"},
		440: {"name": "Lithuania", "code": "LTU"},
		442: {"name": "Luxembourg", "code": "LUX"},
		446: {"name": "Macao", "code": "MAC"},
		450: {"name": "Madagascar", "code": "MDG"},
		454: {"name": "Malawi", "code": "MWI"},
		458: {"name": "Malaysia", "code": "MYS"},
		462: {"name": "Maldives", "code": "MDV"},
		466: {"name": "Mali", "code": "MLI"},
		470: {"name": "Malta", "code": "MLT"},
		474: {"name": "Martinique", "code": "MTQ"},
		478: {"name": "Mauritania", "code": "MRT"},
		480: {"name": "Mauritius", "code": "MUS"},
		484: {"name": "Mexico", "code": "MEX"},
		492: {"name": "Monaco", "code": "MCO"},
		496: {"name": "Mongolia", "code": "MNG"},
		498: {"name": "Republic of Moldova", "code": "MDA"},
		499: {"name": "Montenegro", "code": "MNE"},
		500: {"name": "Montserrat", "code": "MSR"},
		504: {"name": "Morocco", "code": "MAR"},
		508: {"name": "Mozambique", "code": "MOZ"},
		512: {"name": "Oman", "code": "OMN"},
		516: {"name": "Namibia", "code": "NAM"},
		520: {"name": "Nauru", "code": "NRU"},
		524: {"name": "Nepal", "code": "NPL"},
		528: {"name": "Netherlands", "code": "NLD"},
		531: {"name": "Curaçao", "code": "CUW"},
		533: {"name": "Aruba", "code": "ABW"},
		534: {"name": "Sint Maarten", "code": "SXM"},
		535: {"name": "Bonaire, Sint Eustatius and Saba", "code": "BES"},
		540: {"name": "New Caledonia", "code": "NCL"},
		548: {"name": "Vanuatu", "code": "VUT"},
		554: {"name": "New Zealand", "code": "NZL"},
		558: {"name": "Nicaragua", "code": "NIC"},
		562: {"name": "Niger", "code": "NER"},
		566: {"name": "Nigeria", "code": "NGA"},
		570: {"name": "Niue", "code": "NIU"},
		574: {"name": "Norfolk Island", "code": "NFK"},
		578: {"name": "Norway", "code": "NOR"},
		580: {"name": "Northern Mariana Islands", "code": "MNP"},
		581: {"name": "United States Minor Outlying Islands", "code": "UMI"},
		583: {"name": "Federated States of Micronesia", "code": "FSM"},
		584: {"name": "Marshall Islands", "code": "MHL"},
		585: {"name": "Palau", "code": "PLW"},
		586: {"name": "Pakistan", "code": "PAK"},
		591: {"name": "Panama", "code": "PAN"},
		598: {"name": "Papua New Guinea", "code": "PNG"},
		600: {"name": "Paraguay", "code": "PRY"},
		604: {"name": "Peru", "code": "PER"},
		608: {"name": "Philippines", "code": "PHL"},
		612: {"name": "Pitcairn", "code": "PCN"},
		616: {"name": "Poland", "code": "POL"},
		620: {"name": "Portugal", "code": "PRT"},
		624: {"name": "Guinea-Bissau", "code": "GNB"},
		626: {"name": "Timor-Leste", "code": "TLS"},
		630: {"name": "Puerto Rico", "code": "PRI"},
		634: {"name": "Qatar", "code": "QAT"},
		638: {"name": "Réunion", "code": "REU"},
		642: {"name": "Romania", "code": "ROU"},
		643: {"name": "Russian Federation", "code": "RUS"},
		646: {"name": "Rwanda", "code": "RWA"},
		652: {"name": "Saint Barthélemy", "code": "BLM"},
		654: {"name": "Saint Helena", "code": "SHN"},
		659: {"name": "Saint Kitts and Nevis", "code": "KNA"},
		660: {"name": "Anguilla", "code": "AIA"},
		662: {"name": "Saint Lucia", "code": "LCA"},
		663: {"name": "Saint Martin", "code": "MAF"},
		666: {"name": "Saint Pierre and Miquelon", "code": "SPM"},
		670: {"name": "Saint Vincent and the Grenadines", "code": "VCT"},
		674: {"name": "San Marino", "code": "SMR"},
		678: {"name": "Sao Tome and Principe", "code": "STP"},
		682: {"name": "Saudi Arabia", "code": "SAU"},
		686: {"name": "Senegal", "code": "SEN"},
		688: {"name": "Serbia", "code": "SRB"},
		690: {"name": "Seychelles", "code": "SYC"},
		694: {"name": "Sierra Leone", "code": "SLE"},
		702: {"name": "Singapore", "code": "SGP"},
		703: {"name": "Slovakia", "code": "SVK"},
		704: {"name": "Viet Nam", "code": "VNM"},
		705: {"name": "Slovenia", "code": "SVN"},
		706: {"name": "Somalia", "code": "SOM"},
		710: {"name": "South Africa", "code": "ZAF"},
		716: {"name": "Zimbabwe", "code": "ZWE"},
		724: {"name": "Spain", "code": "ESP"},
		728: {"name": "South Sudan", "code": "SSD"},
		729: {"name": "Sudan", "code": "SDN"},
		732: {"name": "Western Sahara", "code": "ESH"},
		740: {"name": "Suriname", "code": "SUR"},
		744: {"name": "Svalbard and Jan Mayen", "code": "SJM"},
		748: {"name": "Swaziland", "code": "SWZ"},
		752: {"name": "Sweden", "code": "SWE"},
		756: {"name": "Switzerland", "code": "CHE"},
		760: {"name": "Syrian Arab Republic", "code": "SYR"},
		762: {"name": "Tajikistan", "code": "TJK"},
		764: {"name": "Thailand", "code": "THA"},
		768: {"name": "Togo", "code": "TGO"},
		772: {"name": "Tokelau", "code": "TKL"},
		776: {"name": "Tonga", "code": "TON"},
		780: {"name": "Trinidad and Tobago", "code": "TTO"},
		784: {"name": "United Arab Emirates", "code": "ARE"},
		788: {"name": "Tunisia", "code": "TUN"},
		792: {"name": "Turkey", "code": "TUR"},
		795: {"name": "Turkmenistan", "code": "TKM"},
		796: {"name": "Turks and Caicos Islands", "code": "TCA"},
		798: {"name": "Tuvalu", "code": "TUV"},
		800: {"name": "Uganda", "code": "UGA"},
		804: {"name": "Ukraine", "code": "UKR"},
		807: {"name": "Republic of Macedonia", "code": "MKD"},
		818: {"name": "Egypt", "code": "EGY"},
		826: {"name": "United Kingdom", "code": "GBR"},
		831: {"name": "Guernsey", "code": "GGY"},
		832: {"name": "Jersey", "code": "JEY"},
		833: {"name": "Isle of Man", "code": "IMN"},
		834: {"name": "United Republic of Tanzania", "code": "TZA"},
		840: {"name": "United States", "code": "USA"},
		850: {"name": "Virgin Islands", "code": "VIR"},
		854: {"name": "Burkina Faso", "code": "BFA"},
		858: {"name": "Uruguay", "code": "URY"},
		860: {"name": "Uzbekistan", "code": "UZB"},
		862: {"name": "Bolivarian Republic of Venezuela", "code": "VEN"},
		876: {"name": "Wallis and Futuna", "code": "WLF"},
		882: {"name": "Samoa", "code": "WSM"},
		887: {"name": "Yemen", "code": "YEM"},
		894: {"name": "Zambia", "code": "ZMB"},
		// custom entries:
		-1:  {"name": "none", "code": "default"},
		901: {"name": "England", "code": "XEN"},
		902: {"name": "Northern Ireland", "code": "XN1"},
		903: {"name": "Scotland", "code": "XSC"},
		904: {"name": "Wales", "code": "XWA"},
		905: {"name": "Europe", "code": "XEU"},
		906: {"name": "Catalan", "code": "CT"},
		737: {"name": "South Sudan", "code": "SS"},
	}
	return countries
}
